name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject API Key into script.js
        run: |
          echo "const GEMINI_API_KEY = '${{ secrets.GEMINI_API_KEY }}';" > ./script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Asegúrate de que el directorio de publicación sea el correcto
